version: '3.5'
services:
  watcher:
    image: scalify/website-content-watcher
    build: .
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=1"
      - "VERBOSE=true"

      - "SMTP_HOST=mailcatcher"
      - "SMTP_PORT=1025"
      - "MAIL_NOTIFIER_ENABLED=true"
      - "MAIL_SENDER_ADDRESS=website-content-watcher@scalify.me"

      - "PUPPET_MASTER_ENDPOINT=http://gateway"
      - "PUPPET_MASTER_API_TOKEN=puppet"
    volumes:
      - "./example:/example"
    command: "watch /example/config.yaml"
    networks:
      - default
      - puppet_master

  redis:
    image: redis:4-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    expose:
      - "1025"
    ports:
      - "1025:1025"
      - "1080:1080"

networks:
  default: {}
  puppet_master:
    external: true
    name: puppet_master
